// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_overpowered = "CgkIlMWJ8uoBEAIQCA"; // <GPGSID>
        public const string achievement_full_power = "CgkIlMWJ8uoBEAIQBQ"; // <GPGSID>
        public const string achievement_one_zero = "CgkIlMWJ8uoBEAIQAg"; // <GPGSID>
        public const string achievement_no_brakes = "CgkIlMWJ8uoBEAIQCQ"; // <GPGSID>
        public const string achievement_half_century = "CgkIlMWJ8uoBEAIQAw"; // <GPGSID>
        public const string achievement_over_99 = "CgkIlMWJ8uoBEAIQBA"; // <GPGSID>
        public const string leaderboard_high_scores = "CgkIlMWJ8uoBEAIQBg"; // <GPGSID>
        public const string achievement_first_death = "CgkIlMWJ8uoBEAIQAQ"; // <GPGSID>

}

